#!/bin/bash

echo "Preparing for install"
if [ $(cat /proc/1/comm) = init ]
then
    stop qvagent || true
elif [ $(cat /proc/1/comm) = systemd ]
then
    echo "-> Systemd detected"
    systemctl is-active snapd.service
    if [ $? -eq 0 ]; then
        # snap service is active and user install qvagent via snap
        snap list | grep "qvagent"
        if [ $? -eq 0 ]; then
            echo "-> qvagent is installed in this instance by snap, please use snap to update or uninstall."
            exit 1
        fi
    fi
    systemctl stop qvagent
    systemctl daemon-reload
fi
